# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [35]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1,2,3,4,5],[6,7,8,9,0]])

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
    [[10,11,12],
    [13,14,16],
    [17,18,19]],
    [[20,21,22],
    [23,24,25],
    [26,27,28]]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d.shape, one_d.ndim, one_d.dtype, one_d.size, type(one_d)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [38]:
# Attributes of 2-dimensional array
# len(two_d.shape) == two_d.ndim
two_d.shape, two_d.ndim, two_d.dtype, two_d.size, type(two_d)

((2, 5), 2, dtype('int64'), 10, numpy.ndarray)

In [40]:
# Attributes of 3-dimensional array
# three_d.size == amount of items in the array
three_d.shape, three_d.ndim, three_d.dtype, three_d.size, type(three_d)

((3, 3, 3), 3, dtype('int64'), 27, numpy.ndarray)

In [37]:
three_d[2][2][1]

27

In [69]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df_one = pd.DataFrame([one_d])
df_two = pd.DataFrame(two_d)
# df_three = pd.DataFrame(three_d) # Cannot do that because array is not 2d, unless we create an array or arrays

In [71]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones(shape=(10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros(shape=(7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [77]:
# Create an array within a range of 0 and 100 with step 3
a1 = np.arange(0, 100, 3, dtype=int)
a1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [80]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a2 = np.random.randint(0, 10, size=(7,2))
a2

array([[2, 3],
       [9, 7],
       [4, 5],
       [0, 3],
       [9, 5],
       [6, 3],
       [3, 2]])

In [81]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a3 = np.random.random((3,5))
a3

array([[0.76693351, 0.79812006, 0.14251641, 0.81458841, 0.1958507 ],
       [0.70189269, 0.12289039, 0.64412663, 0.01894004, 0.96666214],
       [0.21341696, 0.89580907, 0.40347231, 0.35503436, 0.35391109]])

In [82]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a4 = np.random.randint(0, 10, size=(4,6))
a4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [83]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a5 = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(a5)

array([1, 2, 3, 4, 5, 7, 9])

In [89]:
a5

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [117]:
# Find the 0'th index of the latest array you created
# What??
a5[:,0]

array([9, 5, 4])

In [101]:
# Get the first 2 rows of latest array you created
a5[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [115]:
# Get the first 2 values of the first 2 rows of the latest array
a5[0:2,0:2]

array([[9, 1],
       [5, 3]])

In [148]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a6 = np.random.randint(0, 10, size=(3,5))
a7 = np.ones(shape=(3,5))

In [121]:
# Add the two arrays together
a6 + a7

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [122]:
# Create another array of ones of shape (5, 3)
a8 = np.ones(shape=(5,3))

In [123]:
# Try add the array of ones and the other most recent array together
a6 + a8 # sizes are different.

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [124]:
# Create another array of ones of shape (3, 5)
a8 = np.ones(shape=(3,5))

In [125]:
# Subtract the new array of ones from the other most recent array
a6 - a8

array([[-1.,  7.,  5.,  7.,  6.],
       [-1.,  6.,  6.,  1., -1.],
       [ 6.,  1.,  1., -1.,  3.]])

In [126]:
# Multiply the ones array with the latest array
a6 * a8

array([[0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.],
       [7., 2., 2., 0., 4.]])

In [130]:
a6

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [131]:
# Take the latest array to the power of 2 using '**'
a6 ** 2

array([[81, 36, 81, 64, 36],
       [64, 49,  1,  0, 36],
       [36, 49, 16,  4, 49]])

In [132]:
# Do the same thing with np.square()
np.square(a6)

array([[81, 36, 81, 64, 36],
       [64, 49,  1,  0, 36],
       [36, 49, 16,  4, 49]])

In [133]:
# Find the mean of the latest array using np.mean()
np.mean(a6)

5.733333333333333

In [134]:
# Find the maximum of the latest array using np.max()
np.max(a6)

9

In [135]:
# Find the minimum of the latest array using np.min()
np.min(a6)

0

In [136]:
# Find the standard deviation of the latest array
np.std(a6)

2.6948510575210314

In [137]:
# Find the variance of the latest array
np.var(a6)

7.2622222222222215

In [141]:
# Reshape the latest array to (3, 5, 1)
a6.reshape((3,5,1))

array([[[9],
        [6],
        [9],
        [8],
        [6]],

       [[8],
        [7],
        [1],
        [0],
        [6]],

       [[6],
        [7],
        [4],
        [2],
        [7]]])

In [149]:
# Transpose the latest array
a6.T

array([[5, 6, 3],
       [3, 0, 8],
       [9, 0, 2],
       [6, 8, 6],
       [8, 8, 5]])

What does the transpose do?

Flips rows and columns. Or rotates to the right in case of shape (x,y,z) where x,y,z > 1

In [152]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0, 10, size=(3,3))
arr2 = np.random.randint(0, 10, size=(3,2))

In [157]:
arr1, arr1.shape

(array([[1, 1, 5],
        [6, 4, 0],
        [0, 2, 1]]),
 (3, 3))

In [158]:
arr2, arr2.shape

(array([[4, 9],
        [5, 6],
        [3, 6]]),
 (3, 2))

In [156]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1, arr2)

array([[24, 45],
       [44, 78],
       [13, 18]])

In [159]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0, 10, size=(4, 3))
arr4 = np.random.randint(0, 10, size=(4, 3))

In [160]:
# Perform a dot product on the two newest arrays you created
np.dot(arr3, arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

The shapes (4,3) and (4,3) don't match. We'll need to transpose one of the arrays.

In [161]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr3, arr4.T)

array([[29, 24, 44, 21],
       [35, 56, 44, 53],
       [32, 57, 47, 43],
       [39, 82, 54, 64]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [200]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr5 = np.random.randint(0, 30, size=(4, 4))
arr6 = np.random.randint(0, 30, size=(4, 4))

In [187]:
arr5

array([[3, 9, 4, 8],
       [7, 2, 0, 2],
       [3, 1, 0, 6],
       [7, 6, 4, 0]])

In [188]:
arr6

array([[6, 6, 8, 2],
       [8, 0, 0, 3],
       [8, 5, 2, 0],
       [3, 8, 2, 8]])

In [189]:
# Compare the two arrays with '>'
arr5 > arr6 # Elementwise comparison

array([[False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

What happens when you compare the arrays with `>`?

In [190]:
# Compare the two arrays with '>='
arr5 >= arr6 # Elementwise comparison

array([[False,  True, False,  True],
       [False,  True,  True, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [191]:
# Find which elements of the first array are greater than 7
arr5 > 7

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [192]:
# Which parts of each array are equal? (try using '==')
arr5 == arr6

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [217]:
arr5

array([[ 6, 27, 13, 19],
       [18, 25, 14, 15],
       [20,  4,  2, 11],
       [24, 19, 26, 20]])

In [193]:
# Sort one of the arrays you just created in ascending order
np.sort(arr5)

array([[3, 4, 8, 9],
       [0, 2, 2, 7],
       [0, 1, 3, 6],
       [0, 4, 6, 7]])

In [195]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr5)

array([[0, 2, 3, 1],
       [2, 1, 3, 0],
       [2, 1, 0, 3],
       [3, 2, 1, 0]])

In [221]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr5) # flattened array

1

In [223]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr5) # flattened array

10

In [224]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr5, axis=1)

array([1, 1, 0, 2])

In [225]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr5, axis=0)

array([0, 2, 2, 2])

In [233]:
# Create an array of normally distributed random numbers
arr7 = np.random.normal(scale=1, size=(10))
arr7

array([-1.89674722,  0.59909333, -0.16807079,  0.28517532, -0.47191974,
        0.21720648, -0.47187752, -0.55618115, -0.89723633,  1.52582996])

In [240]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr8 = np.linspace(1, 100, num=10)
arr8

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.